### ISSUE TITLE
The letter doesn't seem to show for some users

### ISSUE THREAD

**Issue by Naim2000** [techchrism/letterbomb-web#1]
[please.hackmii.com](https://please.hackmii.com)'s captcha appears to be down right now, however people I've suggested this to have been coming back with mixed results, saying it doesn't show for them, and it doesn't even show for me myself, and even though the LetterBomb itself didn't work in dolphin last time I tried, I mimicked my own Wii's MAC address and it also clearly reflects in the Console information section

**Comment by techchrism** [comment]
I think I must be doing something wrong because I can't even get the original letterbomb (running python locally) to show up on dolphin. Perhaps there's something I'm missing? Here are the steps I'm taking:
- input mac and system menu version
- use Virtual SD Card Maker to make a new 512MB sd image
- mount image using imdisk and extract files from letterbomb zip
- start wii system menu in dolphin and search message board

I ensured I have the date set correctly.
Any tips?

I understand that letterbomb should just crash dolphin instead of launching the hackmii installer but I'm just trying to get the letter to show up.
I might have to dust off my old wii haha.

UPDATE: Turns out I just had the wrong sd card image file selected in dolphin settings
I have confirmed that letterbomb-web doesn't seem to work but the original letterbomb does.

**Comment by techchrism** [comment]
Turns out the problem was some inconsistencies with how daylight savings mode modifies some of the timestamp calculations which is why it was working for some users but not for others.
Should be fixed now.
I also did a quick ui rewrite to reduce the bundle size and support dark mode.

**Comment by techchrism** [comment]
Oh I also changed the url to https://letterbomb.techchrism.me/ and set up a redirect from the old one so nothing breaks

**Comment by Naim2000** [comment]
Oh wow. Thanks. I found out that Wilbrand wasn't showing for me yesterday because Dolphin's SD Card generator just doesn't seem to comply. I'll try this again later today

**Comment by techchrism** [comment]
I used the sd card maker linked from <https://i12bretro.github.io/tutorials/0534.html> and it worked well for me. I haven't tried the dolphin one.

**Comment by Naim2000** [comment]
Sweet.
![image](https://github.com/techchrism/letterbomb-web/assets/44107089/851fcf5e-19e2-4fe2-86fd-656f3805fc56)
